### DISCUSSION TITLE
Status quo: user perspective

### DISCUSSION THREAD

**Discussion by senna1992** [TheMicDiet/chihiros-led-control#37] [Show and tell]
Update I:

Connection is staple if an usb-extension cord is used. this is common for nearby zigbee/Bt/wifi radios since they share the frequency.

-->  i ordered some esp boards to try using them as bt proxies.
--> it might be enabeling me to integrate my fluval light as well - since there's some early stage esp integration for them. 
( https://community.home-assistant.io/t/fluval-aquasky-ble-rgb-light/259598/142?page=7)

//

Big Thanks for making this possible!

As of yesterday, i did not know your integration existed! A hidden gem.

for now i can say that this adapter works (will update list with all conformed good ones from below if posted by someone):'
TP Link UB400 Nano: https://www.amazon.de/gp/product/B07NQ5YGDW

for now i can say that this adapter does not work:
RPI 4 (CM4 with wifi+bt)

this light is detected correctly:
wrgb universal 800mm

this light works, controleld by fallback-mode:
backlight (native support:  brightness change)
c2, after unpairing from app, (native support: brightness change) 
wrgb II 60cm (native support: wrgb + brightness) 

i am currently testing how to combine those lights the rgb lights so, it shows up as one rgb light:

my workaround:
create new helper "input_boolean" -> map it to the state of the entites combined (exclusive and method) -> have an automation set the helper based on the entities state.

my first  "solution" / idea:
have a function node in nodered, which sets all the entites to some predefined level (each has its own level).
add call service node with "service light turn on" after function node
add an helper "input boolean" as  trigger for this function node. 
This way i can have my 2 tanks show the same light scene with no hassle.

my second idea: (how to have 1 entity in HA as quick reference to the light being on or off)

in addition to my time based shedule for switching on and off the lights, i added one more input_boolean helper.
this helper is set to "off" when lights are switched off / on based on the automation.

if this helper is changed manually, it directly triggeres the requested "call service" node, which is part of the given automation.
This helper then can be made visible with "tile" cards or similar, so that it fits visually seemless within light entites.

**Comment by senna1992** [comment]
this is an addition to help with the "generate a virtual light in HA topic":

`light:
  - platform: template
    lights:
      fluval_wrgb:
        unique_id: 28208f257b54c44e50deb2d618d44710
        friendly_name: "wrgb fluval"
        value_template: >-
          {% if is_state('light.aquarium_60l', 'on') %}
            on
          {% else %}
            off
          {% endif %}
        rgbw_template: >
          [
            {{ (state_attr('input_number.lichtstaerke_rot_aq60_hauptlicht', 'value') * 2.55) | int }},
            {{ (state_attr('input_number.lichtstaerke_gruen_aq60_hauptlicht', 'value') * 2.55) | int }},
            {{ (state_attr('input_number.lichtstaerke_blau_aq60_hauptlicht', 'value') * 2.55) | int }},
            {{ (state_attr('input_number.lichtstaerke_weiss_aq60_hauptlicht', 'value') * 2.55) | int }}
          ]
        availability_template: "{{ not is_state('light.fluval_wrgb', 'unknown') }}"
        turn_on:
          service: light.turn_on
          entity_id: light.aquarium_70l
        turn_off:
          service: light.turn_off
          entity_id: light.aquarium_70l
        set_rgbw:
          service: input_number.set_value
          entity_id: light.fluval_wrgb
          data:
            rgbw_color:
              - "{{ (r / 2.55) | int }}"
              - "{{ (g / 2.55) | int }}"
              - "{{ (b / 2.55) | int }}"
              - "{{ (w / 2.55) | int }}"
 `

this will give you a entity that has rgbw support and color wheel etc.
currently i am working on connecting this to some input_numbers. over here:
[https://community.home-assistant.io/t/fluval-aquasky-ble-rgb-light/259598/144](url)

this might be helpful as well:
[https://www.home-assistant.io/integrations/light.template/](url)


Ps: your integration works great for me now =)

**Comment by TheMicDiet** [comment]
Hi @senna1992, could you provide me the device ids of your devices that currently use the fallback so that I can add the corresponding model codes for auto detection of the corresponding device class?

**Reply by senna1992** [reply]
regarding the update 0.4.1, i just had a look at it and found, taht wrgb universal has been removed from supported,
has it been integrated into the wrgb ii detection?

it is highly different compared to the wrgb ii (pro).
[more powerful, not for lid-closed tanks etc]

it might be easier to separate the lights in these categories:

--> WRGB-lights [iE universal, pro, aniversairy, ii , c2 rgb edition]
--> brightness only white light [iE c2]

**Reply by TheMicDiet** [reply]
I didn't change anything regarding WRGB universal, as for now each device has its own class. There are also more difference e.g. there is also a single color green LED or RGB only LEDs without a white channel.

**Comment by senna1992** [comment]
Hi sure :)


This is the ID of chihiros backlight (setting: brightness only) "dycomffb36c71c2bf"


This is the ID of chihiros C2 (setting: brightness only) "dync2ncb08109274d1"

This is the ID of chihiros wrgb 2 (settings: rgb, white) "DYNWRGBF64B5365158E"


:)

________________________________

**Reply by TheMicDiet** [reply]
Thank you, I will add support for C2 (none RGB) and the backlight. The WRGB 2 with your device id should be already supported.

**Reply by senna1992** [reply]
Just updated to 0.4.1 and rebooted. Then remove and re add to the integration.


Still detected as fallback. Any more logs I can provide you with? 
[error_log.bin.txt](https://github.com/user-attachments/files/16823866/error_log.bin.txt)

**Reply by TheMicDiet** [reply]
I don't know to be honest.  The detection works by taking the prefix of the device id, i.e. throwing away the last 12 characters. For WRGB 2, "DYNWRGB" is one of the possible model codes (prefixes) that clearly matches your device id.

**Reply by TheMicDiet** [reply]
I also added support for C2 non-RGB and the backlight now. maybe you can try and see if they are detected

**Reply by senna1992** [reply]
Update by use of 0.5.0

--> Backlight detected correctly! :)
--> C2 still on fallback (ID "DYNC2NCB08109274D1")
--> WRGBii still on fallback (ID "DYNWRGBF64B5365158E"

**Reply by TheMicDiet** [reply]
Okay, I will see if I can add some more logging to find out why the detection is not working and get back to you.

**Reply by senna1992** [reply]
The issue you're encountering likely stems from a small typo in the class definition for the CII device. Specifically, the _model_code attribute should be _model_codes to match the expected attribute name used in the code that populates the CODE2MODEL dictionary.



Hope that helps =)

**Reply by TheMicDiet** [reply]
Thanks for the hint 👍. I fixed it in 0.5.1, hopefully it works now.

**Reply by senna1992** [reply]
![2024-08-31 11 19 40 192 168 0 42 dae34d69c218](https://github.com/user-attachments/assets/cf79d127-9049-482f-865a-ef9d404ae510)


You did it!


Also the detection went form fallback to the specific model without having to remove and readd the device, thus keeping entities alive

**Comment by senna1992** [comment]
![2024-09-05 18 49 31 192 168 0 42 9036f2fab6bf](https://github.com/user-attachments/assets/a564909c-759b-4c2b-908a-43a8c14f5f7c)
This is for you, if you want control like the lights you used to:

This part is for the virtual input_boolean entity mapped to all the light entites (iE with nodeRed):
[all on -> boolen on ; all off -> boolean off]
 
```
      - type: tile
        entity: input_boolean.beleuchtung_aquarium_60l
        name: Beleuchtung
        tap_action:
          action: toggle
```
This part is for the sliders. 
Based on the mushroom light card and "mushroom better sliders" from hacs.


```
      - type: custom:mushroom-light-card
        entity: light.aquarium_60l_red
        icon_color: red
        show_color_control: false
        collapsible_controls: false
        show_brightness_control: true
        primary_info: none
        icon_type: none
        secondary_info: none
        layout: vertical
        fill_container: false
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
      - type: custom:mushroom-light-card
        entity: light.aquarium_60l_blue
        icon_color: blue
        show_color_control: false
        collapsible_controls: false
        show_brightness_control: true
        primary_info: none
        icon_type: none
        secondary_info: none
        layout: vertical
        fill_container: false
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
      - type: custom:mushroom-light-card
        entity: light.aquarium_60l_green
        icon_color: green
        show_color_control: false
        collapsible_controls: false
        show_brightness_control: true
        primary_info: none
        icon_type: none
        secondary_info: none
        layout: vertical
        fill_container: false
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
      - type: custom:mushroom-light-card
        entity: light.aquarium_60l_white
        icon_color: white
        show_color_control: false
        collapsible_controls: false
        show_brightness_control: true
        primary_info: none
        icon_type: none
        secondary_info: none
        layout: vertical
        fill_container: false
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
    columns: 1
```
